---
- name: Install 7-Zip on Windows
  hosts: active_host
  gather_facts: false

  tasks:
    - name: Install 7-Zip
      ansible.windows.win_package:
        path: 'https://www.7-zip.org/a/7z1900-x64.exe'
        arguments: '/S'
        state: present
