---
- name: Install Adobe Acrobat XI Standard MSI with MST
  hosts: windows_server
  gather_facts: false

  tasks:
    - name: Install Acrobat XI using MSI + MST
      ansible.windows.win_package:
        path: '\\W-SERVER\Users\Administrator\EXE_Folder\Adobe\AcroStan.msi'
        arguments: 'TRANSFORMS="\\W-SERVER\Users\Administrator\EXE_Folder\Adobe\AcroStan.mst" /qn /l*v C:\Temp\acrobat_install.log'
        state: present
