---
- name: Install packages
  hosts: windows_server
  become: false
  gather_facts: false
  vars:
    packages:
      - git
      # - notepadplusplus
  tasks:
    - name: Install packages via Chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
        state: present
