- name: Install VMware Tools
  hosts: active_host
  gather_facts: false
  tasks:
    - name: Install vmware-tools via Chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name: vmware-tools
        state: present
